name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    ## load application
    - uses: actions/checkout@v4

    ## jdk setting
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    ## create application-secret.yml
    - name: create application-secret.yml
      run: |
        cd ./src/main/resources
        touch ./application-secret.yml
        echo "${{ secrets.APPLICATION_SECRET }}" | base64 --decode > ./application-secret.yml
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    ## docker build & push
    - name: Docker build
      run: |
       echo "${{ secrets.DOCKER_TOKEN }}" | base64 --decode | docker login -u $(echo "${{ secrets.DOCKER_USERNAME }}" | base64 --decode) --password-stdin

        docker build -t app .
        docker tag app $(echo "${{ secrets.DOCKER_USERNAME }}" | base64 --decode)/solta:latest
        docker push $(echo "${{ secrets.DOCKER_USERNAME }}" | base64 --decode)/solta:latest

    ## docker deploy to EC2
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        debug: true
        script: |
          docker pull $(echo "${{ secrets.DOCKER_USERNAME }}" | base64 --decode)/solta:latest
          docker stop $(docker ps -a -q)
          docker run -d --log-driver=syslog -p 8080:8080 $(echo "${{ secrets.DOCKER_USERNAME }}" | base64 --decode)/solta:latest
          docker rm $(docker ps --filter 'status=exited' -a -q)
          docker image prune -a -f
